<?php
session_start();
$url = file_get_contents("../../../conexion/credencial.json");
$credencial= json_decode($url, true);
require_once "../../../libreria/PHPExcel/Classes/PHPExcel.php";
require_once "../../../libreria/PHPExcel/Classes/PHPExcel/Reader/Excel2007.php";
require_once "../../../libreria/PHPExcel/Classes/PHPExcel/IOFactory.php";
require_once "../clase/Actividad.php";
$actividad = new Actividad($credencial['driver'],$credencial['host'], $credencial['user'], $credencial['pwd'],$credencial['database']);
$result = $actividad->listarActividad($_REQUEST);

$objPHPExcel = new PHPExcel();

    $objPHPExcel->getProperties()->setCreator("AsoAtlantico")
            ->setLastModifiedBy("SID")
            ->setTitle("Office 2007 XLSX Actividades")
            ->setSubject("Office 2007 XLSX Actividades")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("Actividades");

    $objDrawing = new PHPExcel_Worksheet_Drawing();
    $objDrawing->setName('PHPExcel logo');
    $objDrawing->setDescription('PHPExcel logo');
    $objDrawing->setPath('../../../libreria/img/logo.png');
    $objDrawing->setHeight(80);
    $objDrawing->setCoordinates('A3');
    $objDrawing->setOffSetX(20);
    $objDrawing->setRotation(0);
    $objDrawing->getShadow()->setVisible(true);
    $objDrawing->getShadow()->setDirection(0);
    $objDrawing->SetWorksheet($objPHPExcel->getActiveSheet());

    $objPHPExcel->getActiveSheet()->setTitle('Actividades');
    $objPHPExcel->getActiveSheet()->getStyle('A3:N3')->getFont()->setName('Arial');
    $objPHPExcel->getActiveSheet()->getStyle('A3:N3')->getFont()->setSize(12);
    $objPHPExcel->getActiveSheet()->mergeCells('A3:N3');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, 3, 'REPORTE ACTIVIDADES EN TERRENO');
    $objPHPExcel->getActiveSheet()->getStyle('A3:N3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('A3:N3')->getFont()->setBold(true);

    $objPHPExcel->getActiveSheet()->getStyle('O3:Q3')->getFont()->setName('Arial');
    $objPHPExcel->getActiveSheet()->getStyle('O3:Q3')->getFont()->setSize(8);
    $objPHPExcel->getActiveSheet()->mergeCells('O3:Q3');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(14, 3, "GENERADO POR: ".$_SESSION['nombre']." ".$_SESSION['apellido']."\n FECHA GENERACION:".date("Y-m-d"));
    $objPHPExcel->getActiveSheet()->getStyle('O3:Q3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('O3:Q3')->getFont()->setBold(true);

    $objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(80);


    $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('J')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('K')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('L')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('M')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('N')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('O')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('P')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('Q')->setAutoSize(true);

    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, 9, '#');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, 9, 'MUNICIPIO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, 9, 'POSTE NO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, 9, 'LUMINARIA NO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, 9, 'TIPO LUMINARIA');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, 9, 'BARRIO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, 9, 'DIRECCION');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, 9, 'TIPO ACTIVIDAD');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, 9, 'FCHA ACTIVIDAD');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(9, 9, 'FCH REPORTE');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(10, 9, 'TIPO REPORTE');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(11, 9, 'RADICADO PQR');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(12, 9, 'TIPO PQR');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(13, 9, 'EJECUTA');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(14, 9, 'VEHICULO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(15, 9, 'ESTADO ACTIVIDAD');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(16, 9, 'OBSERVACION');

    $row = 10;
    $item = 1;
    while (!$result->EOF) {
        
        //$objPHPExcel->getActiveSheet()->getRowDimension($row)->setRowHeight(60);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, $row, strval($item));
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, $row, $result->fields["municipio"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, $row, $result->fields["poste_no"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, $row, $result->fields["luminaria_no"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, $row, $result->fields["tipo_luminaria"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, $row, $result->fields["barrio"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, $row, $result->fields["direccion"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, $row, $result->fields["tipo"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, $row, $result->fields['fch_actividad']);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(9, $row, $result->fields["fch_reporte"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(10, $row, $result->fields["tipo_reporte"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(11, $row, $result->fields["id_pqr"]);  
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(12, $row, $result->fields["tipo_pqr"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(13, $row, $result->fields["tecnico"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(14, $row, $result->fields["vehiculo"]);  
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(15, $row, $result->fields["estado_actividad"]);    
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(16, $row, $result->fields["observacion"]);    
        
        $result->MoveNext();
        $row++;
        $item++;
    }
    $nombre = 'actividades_asoatlantico' . rand() . '.xlsx';

    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
    $objWriter->save($nombre);

    header("Content-Disposition: attachment; filename=" . $nombre);
    header("Content-Type: application/vnd.ms-excel");
    header("Content-Length: " . filesize($nombre));
    readfile($nombre);
    unlink($nombre);
?>