<?php
session_start();
$url = file_get_contents("../../../conexion/credencial.json");
$credencial= json_decode($url, true);
require_once "../../../libreria/PHPExcel/Classes/PHPExcel.php";
require_once "../../../libreria/PHPExcel/Classes/PHPExcel/Reader/Excel2007.php";
require_once "../../../libreria/PHPExcel/Classes/PHPExcel/IOFactory.php";
require_once "../clase/Liquidacion.php";
require_once "../../global/global.php";
$liquidacion  = new Liquidacion($credencial['driver'],$credencial['host'], $credencial['user'], $credencial['pwd'],$credencial['database']);
$result = $liquidacion->listarLiquidacion($_REQUEST);

$objPHPExcel = new PHPExcel();

    $objPHPExcel->getProperties()->setCreator("AsoAtlantico")
            ->setLastModifiedBy("ATL")
            ->setTitle("Office 2007 XLSX Luminaria")
            ->setSubject("Office 2007 XLSX Luminaria")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("Luminaria");

    $objDrawing = new PHPExcel_Worksheet_Drawing();
    $objDrawing->setName('PHPExcel logo');
    $objDrawing->setDescription('PHPExcel logo');
    $objDrawing->setPath('../../../libreria/img/logo.png');
    $objDrawing->setHeight(80);
    $objDrawing->setCoordinates('A3');
    $objDrawing->setOffSetX(20);
    $objDrawing->setRotation(0);
    $objDrawing->getShadow()->setVisible(true);
    $objDrawing->getShadow()->setDirection(0);
    $objDrawing->SetWorksheet($objPHPExcel->getActiveSheet());

    $objPHPExcel->getActiveSheet()->setTitle('Luminaria');
    $objPHPExcel->getActiveSheet()->getStyle('A3:J3')->getFont()->setName('Arial');
    $objPHPExcel->getActiveSheet()->getStyle('A3:J3')->getFont()->setSize(12);
    $objPHPExcel->getActiveSheet()->mergeCells('A3:J3');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, 3, 'REPORTE LIQUIDACION');
    $objPHPExcel->getActiveSheet()->getStyle('A3:J3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('A3:J3')->getFont()->setBold(true);

    $objPHPExcel->getActiveSheet()->getStyle('K3:M3')->getFont()->setName('Arial');
    $objPHPExcel->getActiveSheet()->getStyle('K3:M3')->getFont()->setSize(8);
    $objPHPExcel->getActiveSheet()->mergeCells('K3:M3');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(10, 3, "GENERADO POR: ".$_SESSION['nombre']." ".$_SESSION['apellido']."\n FECHA GENERACION:".date("Y-m-d"));
    $objPHPExcel->getActiveSheet()->getStyle('K3:M3')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle('K3:M3')->getFont()->setBold(true);

    $objPHPExcel->getActiveSheet()->getRowDimension(3)->setRowHeight(80);


    $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('E')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('F')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('G')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('H')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('I')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('J')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('K')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('L')->setAutoSize(true);
    $objPHPExcel->getActiveSheet()->getColumnDimension('M')->setAutoSize(true);

    
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, 9, '#');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, 9, 'MUNICIPIO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, 9, 'PERIODO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, 9, 'MES');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, 9, 'CONSUMO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, 9, 'TARIFA');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, 9, 'VALOR CONSUMO');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, 9, 'FACT ENERGIA');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, 9, 'FACT IMP AP');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(9, 9, 'FACT TSYCC');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(10, 9, 'DIF FACTURACION');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(11, 9, 'RECAUDO IMP AP');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(12, 9, 'RECAUDO TSYCC');
    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(13, 9, 'DIF RECAUDO');

    $row = 10;
    $item = 1;
    while (!$result->EOF) {
        
        $dif_facturacion = number_format(($result->fields['facturacion_impuesto_ap']-$result->fields['facturacion_tsycc']),2,',','');
        $dif_recaudo = number_format(($result->fields['recaudo_impuesto_ap']-$result->fields['recaudo_tsycc']),2,',','');

        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, $row, strval($item));
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, $row, $result->fields["municipio"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, $row, $result->fields["periodo_liquidacion"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, $row, strtoupper(nombreMeses($result->fields['mes_liquidacion'])));
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, $row, $result->fields["consumo"]);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, $row, number_format($result->fields["valor_tarifa"],2,',',''));
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, $row, number_format($result->fields["valor_consumo"],2,',',''));
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, $row, number_format($result->fields["facturacion_energia"],2,',',''));
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, $row, number_format($result->fields['facturacion_impuesto_ap']),2,',','');
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(9, $row, number_format($result->fields["facturacion_tsycc"],2,',',''));
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(10, $row, $dif_facturacion);
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(11, $row, number_format($result->fields["recaudo_impuesto_ap"],2,',',''));      
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(12, $row, number_format($result->fields["recaudo_tsycc"],2,',',''));      
        $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(13, $row, $dif_recaudo);      

        $result->MoveNext();
        $row++;
        $item++;
    }
    $nombre = 'liquidacion_asoatlantico' . rand() . '.xlsx';

    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
    $objWriter->save($nombre);

    header("Content-Disposition: attachment; filename=" . $nombre);
    header("Content-Type: application/vnd.ms-excel");
    header("Content-Length: " . filesize($nombre));
    readfile($nombre);
    unlink($nombre);
?>